package com.mahesaiqbal.recyclerviewkotlin

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.support.v7.widget.LinearLayoutManager
import android.support.v7.widget.RecyclerView
import com.mahesaiqbal.recyclerviewkotlin.adapter.CountryAdapter

class MainActivity : AppCompatActivity() {

    lateinit var countryList: RecyclerView
    var countries: MutableList<String> = ArrayList()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        addData()

        countryList = findViewById(R.id.country_list) as RecyclerView
        countryList.layoutManager = LinearLayoutManager(this)
//        countryList.layoutManager = GridLayoutManager(this, 2)
        countryList.adapter = CountryAdapter(countries, this)
    }

    fun addData() {
        countries.add("Afganistan")
        countries.add("Afrika Selatan")
        countries.add("Afrika Tengah")
        countries.add("Albania")
        countries.add("Aljazair")
        countries.add("Amerika Serikat")
        countries.add("Andorra")
        countries.add("Angola")
        countries.add("Antigua dan Barbuda")
        countries.add("Arab Saudi")
        countries.add("Argentina")
        countries.add("Armenia")
        countries.add("Australia")
        countries.add("Austria")
        countries.add("Azerbaijan")
        countries.add("Bahama")
        countries.add("Bahrain")
        countries.add("Bangladesh")
        countries.add("Barbados")
        countries.add("Belanda")
        countries.add("Belarus")
        countries.add("Belgia")
        countries.add("Belize")
        countries.add("Benin")
        countries.add("Bhutan")
        countries.add("Bolivia")
        countries.add("Bosnia dan Herzegovina")
        countries.add("Botswana")
        countries.add("Brasil")
        countries.add("Britania Raya")
        countries.add("Brunei Darussalam")
        countries.add("Bulgaria")
        countries.add("Burkina Faso")
        countries.add("Burundi")
        countries.add("Ceko")
        countries.add("Chad")
        countries.add("Chili")
        countries.add("China")
        countries.add("Denmark")
        countries.add("Djibouti")
        countries.add("Dominika")
        countries.add("Ekuador")
        countries.add("El Salvador")
        countries.add("Eritrea")
        countries.add("Estonia")
        countries.add("Ethiopia")
        countries.add("Fiji")
        countries.add("Filipina")
        countries.add("Finlandia")
        countries.add("Gabon")
        countries.add("Gambia")
        countries.add("Georgia")
        countries.add("Ghana")
        countries.add("Grenada")
        countries.add("Guatemala")
        countries.add("Guinea")
        countries.add("Guinea Bissau")
        countries.add("Guinea Khatulistiwa")
        countries.add("Guyana")
        countries.add("Haiti")
        countries.add("Honduras")
        countries.add("Hongaria")
        countries.add("India")
        countries.add("Indonesia")
        countries.add("Irak")
        countries.add("Iran")
        countries.add("Irlandia")
        countries.add("Islandia")
        countries.add("Israel")
        countries.add("Italia")
        countries.add("Jamaika")
        countries.add("Jepang")
        countries.add("Jerman")
        countries.add("Kamboja")
        countries.add("Kamerun")
        countries.add("Kanada")
        countries.add("Kazakhstan")
        countries.add("Kenya")
        countries.add("Kirgizstan")
        countries.add("Kiribati")
        countries.add("Kolombia")
        countries.add("Komoro")
        countries.add("Republik Kongo")
        countries.add("Korea Selatan")
        countries.add("Korea Utara")
        countries.add("Kosta Rika")
        countries.add("Kroasia")
        countries.add("Kuba")
        countries.add("Kuwait")
        countries.add("Laos")
        countries.add("Latvia")
        countries.add("Lebanon")
        countries.add("Lesotho")
        countries.add("Liberia")
        countries.add("Libya")
        countries.add("Liechtenstein")
        countries.add("Lituania")
        countries.add("Luksemburg")
        countries.add("Madagaskar")
        countries.add("Makedonia")
    }
}
